export const evData = [
    {
      vin: "KNDC3DLC3N",
      county: "King",
      city: "Seattle",
      state: "WA",
      zipCode: "98118",
      modelYear: 2022,
      make: "KIA",
      model: "EV6",
      fuelType: "Battery Electric Vehicle (BEV)",
      eligibilityStatus: "Eligibility unknown as battery range has not been researched",
      batteryRange: 0,
      otherRange: 0,
      emissionsScore: 37,
      registrationId: 209298442,
      coordinates: "POINT (-122.28339 47.549285)",
      utilityProviders: "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
      censusTract: 53033010200,
    },
    {
      vin: "7SAYGDEEXN",
      county: "King",
      city: "Issaquah",
      state: "WA",
      zipCode: "98029",
      modelYear: 2022,
      make: "TESLA",
      model: "MODEL Y",
      fuelType: "Battery Electric Vehicle (BEV)",
      eligibilityStatus: "Eligibility unknown as battery range has not been researched",
      batteryRange: 0,
      otherRange: 0,
      emissionsScore: 5,
      registrationId: 220415555,
      coordinates: "POINT (-121.9993659 47.5484866)",
      utilityProviders: "PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)",
      censusTract: 53033032221,
    },
    {
      vin: "KNDCC3LG4N",
      county: "King",
      city: "Seattle",
      state: "WA",
      zipCode: "98125",
      modelYear: 2022,
      make: "KIA",
      model: "NIRO",
      fuelType: "Battery Electric Vehicle (BEV)",
      eligibilityStatus: "Eligibility unknown as battery range has not been researched",
      batteryRange: 0,
      otherRange: 0,
      emissionsScore: 46,
      registrationId: 205703410,
      coordinates: "POINT (-122.296385 47.71558)",
      utilityProviders: "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
      censusTract: 53033000202,
    },
    {
      vin: "JTJHKCFZ1R",
      county: "King",
      city: "Bellevue",
      state: "WA",
      zipCode: "98006",
      modelYear: 2024,
      make: "LEXUS",
      model: "NX",
      fuelType: "Plug-in Hybrid Electric Vehicle (PHEV)",
      eligibilityStatus: "Clean Alternative Fuel Vehicle Eligible",
      batteryRange: 37,
      otherRange: 0,
      emissionsScore: 41,
      registrationId: 259163628,
      coordinates: "POINT (-122.16937 47.571015)",
      utilityProviders: "PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)",
      censusTract: 53033025007,
    },
    {
      vin: "JTDKARFP8L",
      county: "Clark",
      city: "Vancouver",
      state: "WA",
      zipCode: "98682",
      modelYear: 2020,
      make: "TOYOTA",
      model: "PRIUS PRIME",
      fuelType: "Plug-in Hybrid Electric Vehicle (PHEV)",
      eligibilityStatus: "Not eligible due to low battery range",
      batteryRange: 25,
      otherRange: 0,
      emissionsScore: 17,
      registrationId: 168387299,
      coordinates: "POINT (-122.5146473 45.67862)",
      utilityProviders: "BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLARK COUNTY - (WA)",
      censusTract: 53011040604,
    },
    {
        vin: "KNDC3DLC3N",
        county: "King",
        city: "Seattle",
        state: "WA",
        zipCode: "98118",
        modelYear: 2022,
        make: "KIA",
        model: "EV6",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligibility unknown as battery range has not been researched",
        batteryRange: 0,
        otherRange: 0,
        emissionsScore: 37,
        registrationId: 209298442,
        coordinates: "POINT (-122.28339 47.549285)",
        utilityProviders: "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
        censusTract: 53033010200,
      },
      {
        vin: "7SAYGDEEXN",
        county: "King",
        city: "Issaquah",
        state: "WA",
        zipCode: "98029",
        modelYear: 2022,
        make: "TESLA",
        model: "MODEL Y",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligibility unknown as battery range has not been researched",
        batteryRange: 0,
        otherRange: 0,
        emissionsScore: 5,
        registrationId: 220415555,
        coordinates: "POINT (-121.9993659 47.5484866)",
        utilityProviders: "PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)",
        censusTract: 53033032221,
      },
      {
        vin: "KNDCC3LG4N",
        county: "King",
        city: "Seattle",
        state: "WA",
        zipCode: "98125",
        modelYear: 2022,
        make: "KIA",
        model: "NIRO",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligibility unknown as battery range has not been researched",
        batteryRange: 0,
        otherRange: 0,
        emissionsScore: 46,
        registrationId: 205703410,
        coordinates: "POINT (-122.296385 47.71558)",
        utilityProviders: "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
        censusTract: 53033000202,
      },
      {
        vin: "JTJHKCFZ1R",
        county: "King",
        city: "Bellevue",
        state: "WA",
        zipCode: "98006",
        modelYear: 2024,
        make: "LEXUS",
        model: "NX",
        fuelType: "Plug-in Hybrid Electric Vehicle (PHEV)",
        eligibilityStatus: "Clean Alternative Fuel Vehicle Eligible",
        batteryRange: 37,
        otherRange: 0,
        emissionsScore: 41,
        registrationId: 259163628,
        coordinates: "POINT (-122.16937 47.571015)",
        utilityProviders: "PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)",
        censusTract: 53033025007,
      },
      {
        vin: "JTDKARFP8L",
        county: "Clark",
        city: "Vancouver",
        state: "WA",
        zipCode: "98682",
        modelYear: 2020,
        make: "TOYOTA",
        model: "PRIUS PRIME",
        fuelType: "Plug-in Hybrid Electric Vehicle (PHEV)",
        eligibilityStatus: "Not eligible due to low battery range",
        batteryRange: 25,
        otherRange: 0,
        emissionsScore: 17,
        registrationId: 168387299,
        coordinates: "POINT (-122.5146473 45.67862)",
        utilityProviders: "BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLARK COUNTY - (WA)",
        censusTract: 53011040604,
      },
      {
        vin: "5YJSA1CN1DF",
        county: "Snohomish",
        city: "Everett",
        state: "WA",
        zipCode: "98203",
        modelYear: 2021,
        make: "TESLA",
        model: "MODEL S",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligible for full clean fuel rebate",
        batteryRange: 348,
        otherRange: 0,
        emissionsScore: 2,
        registrationId: 210345600,
        coordinates: "POINT (-122.239517 47.913508)",
        utilityProviders: "SNOHOMISH COUNTY PUD NO 1",
        censusTract: 53061040401,
      },
      {
        vin: "4T1K61AK4MU",
        county: "Pierce",
        city: "Tacoma",
        state: "WA",
        zipCode: "98445",
        modelYear: 2023,
        make: "TOYOTA",
        model: "CAMRY",
        fuelType: "Hybrid Electric Vehicle (HEV)",
        eligibilityStatus: "Not eligible for clean fuel rebate",
        batteryRange: 25,
        otherRange: 0,
        emissionsScore: 15,
        registrationId: 218034567,
        coordinates: "POINT (-122.42033 47.172208)",
        utilityProviders: "TACOMA PUBLIC UTILITIES",
        censusTract: 53053060301,
      },
      {
        vin: "1G1RC6E46EU",
        county: "Spokane",
        city: "Spokane",
        state: "WA",
        zipCode: "99207",
        modelYear: 2019,
        make: "CHEVROLET",
        model: "VOLT",
        fuelType: "Plug-in Hybrid Electric Vehicle (PHEV)",
        eligibilityStatus: "Eligible for partial clean fuel rebate",
        batteryRange: 53,
        otherRange: 0,
        emissionsScore: 24,
        registrationId: 176540890,
        coordinates: "POINT (-117.392328 47.679318)",
        utilityProviders: "AVISTA UTILITIES",
        censusTract: 53063012702,
      },
      {
        vin: "WAUZL64B21N",
        county: "Thurston",
        city: "Olympia",
        state: "WA",
        zipCode: "98501",
        modelYear: 2021,
        make: "AUDI",
        model: "E-TRON",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligible for full clean fuel rebate",
        batteryRange: 222,
        otherRange: 0,
        emissionsScore: 12,
        registrationId: 203567441,
        coordinates: "POINT (-122.900695 47.037874)",
        utilityProviders: "PUGET SOUND ENERGY INC",
        censusTract: 53067000200,
      },
      {
        vin: "WVWBP7AN0BE",
        county: "King",
        city: "Kent",
        state: "WA",
        zipCode: "98030",
        modelYear: 2022,
        make: "VOLKSWAGEN",
        model: "ID.4",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligibility unknown as battery range has not been researched",
        batteryRange: 250,
        otherRange: 0,
        emissionsScore: 22,
        registrationId: 222034502,
        coordinates: "POINT (-122.23476 47.380933)",
        utilityProviders: "PUGET SOUND ENERGY INC",
        censusTract: 53033020400,
      },
      {
        vin: "3N1CP5DV3LL",
        county: "Yakima",
        city: "Yakima",
        state: "WA",
        zipCode: "98902",
        modelYear: 2021,
        make: "NISSAN",
        model: "LEAF",
        fuelType: "Battery Electric Vehicle (BEV)",
        eligibilityStatus: "Eligible for partial clean fuel rebate",
        batteryRange: 149,
        otherRange: 0,
        emissionsScore: 19,
        registrationId: 198745632,
        coordinates: "POINT (-120.53158 46.602071)",
        utilityProviders: "PACIFIC POWER",
        censusTract: 53077000203,
      }
  ];
  